name: Core
version: 1.0.0
author: anthognie
main: fr.anthognie.Core.Main
api-version: '1.20'
description: Plugin Core pour l'économie et les données.
commands:
  money:
    description: Gère l'économie du serveur.
    aliases: [ bal, balance, eco ]
  itemdb:
    description: Ouvre la base de données d'items moddés.
    aliases: [ itemdatabase ]
    permission: callofdusty.admin
  buildmode:
    description: Active/Désactive le mode build pour les admins.
    aliases: [ bm ]
    permission: callofdusty.admin